### ISSUE TITLE
Consider adding a license file

### ISSUE THREAD

**Issue by marschall** [mhewedy/spwrap#26]
The project is Apache 2 licensed but one has to the scroll to the bottom to find out. Github has support for [LICENSE](https://help.github.com/articles/licensing-a-repository/) files which cause the licensing information to be prominently displayed.

**Comment by marschall** [comment]
Ideally a license section would be added to the POM as well.
https://maven.apache.org/pom.html#Licenses

**Comment by mhewedy** [comment]
Fixed, Thanks.
