### ISSUE TITLE
Add jars to maven central repository

### ISSUE THREAD

**Issue by joineral32** [mhewedy/spwrap#30]
Please add these to the maven central repository

**Comment by mhewedy** [comment]
I'll work on it, but why not use it via jitpack.io?

**Comment by marschall** [comment]
@mhewedy everything that's not Maven Central is a bit tougher to work with. If you're behind a repository manager like Nexus you'll need to add the repository there and probably add some access rules. If you're not behind a repository manager you'll need to add it to `settings.xml` and hope it behaves well. Adding it directly to `pom.xml` is not recommended. Adding it to Maven Central adds a little bit of security and convenience.

**Comment by joineral32** [comment]
There would be very serious security concerns with adding some random 3rd party remote repository to our nexus installation. There is absolutely no way I can do that. For the most part, if your stuff isn't in the maven central repository with PGP signatures, most people can't/won't use it.

**Comment by mhewedy** [comment]
@marschall @joineral32 thanks for clarifications, I am working on it.

**Comment by mhewedy** [comment]
I've created this ticket to deploy the project to the maven repository https://issues.sonatype.org/browse/OSSRH-28783

**Comment by mhewedy** [comment]
Issue fixed, and you can include it in mvn (gradle and other build tools) without adding jitpack, however it still not searchable in mvn central repo.

**Comment by marschall** [comment]
The sync with Maven Central may take a few hours, it's available now:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spwrap%22
